import { Car, Campaign } from "./types";

export const MOCK_CARS: Car[] = [
  {
    id: "car-1",
    make: "Toyota",
    model: "Camry",
    year: 2024,
    price: 28500,
    image: "https://placehold.co/600x400/1a1a2e/e0e0e0?text=Toyota+Camry",
    color: "Midnight Black",
    mileage: 0,
    fuelType: "Hybrid",
    features: ["Apple CarPlay", "Lane Assist", "Adaptive Cruise"],
  },
  {
    id: "car-2",
    make: "Honda",
    model: "Civic",
    year: 2024,
    price: 24800,
    image: "https://placehold.co/600x400/16213e/e0e0e0?text=Honda+Civic",
    color: "Sonic Gray",
    mileage: 0,
    fuelType: "Gasoline",
    features: ["Honda Sensing", "Wireless CarPlay", "LED Headlights"],
  },
  {
    id: "car-3",
    make: "Ford",
    model: "Mustang",
    year: 2024,
    price: 32900,
    image: "https://placehold.co/600x400/0f3460/e0e0e0?text=Ford+Mustang",
    color: "Race Red",
    mileage: 0,
    fuelType: "Gasoline",
    features: ["V8 Engine", "Track Apps", "Performance Pack"],
  },
  {
    id: "car-4",
    make: "BMW",
    model: "3 Series",
    year: 2024,
    price: 44500,
    image: "https://placehold.co/600x400/533483/e0e0e0?text=BMW+3+Series",
    color: "Alpine White",
    mileage: 0,
    fuelType: "Gasoline",
    features: ["iDrive 8", "Parking Assistant", "Harman Kardon"],
  },
  {
    id: "car-5",
    make: "Tesla",
    model: "Model 3",
    year: 2024,
    price: 42000,
    image: "https://placehold.co/600x400/2c3e50/e0e0e0?text=Tesla+Model+3",
    color: "Pearl White",
    mileage: 0,
    fuelType: "Electric",
    features: ["Autopilot", "15\" Touchscreen", "Over-the-air Updates"],
  },
  {
    id: "car-6",
    make: "Mercedes-Benz",
    model: "C-Class",
    year: 2024,
    price: 46800,
    image: "https://placehold.co/600x400/34495e/e0e0e0?text=Mercedes+C-Class",
    color: "Obsidian Black",
    mileage: 0,
    fuelType: "Gasoline",
    features: ["MBUX", "Burmester Audio", "AMG Line"],
  },
  {
    id: "car-7",
    make: "Chevrolet",
    model: "Equinox",
    year: 2024,
    price: 28900,
    image: "https://placehold.co/600x400/1abc9c/ffffff?text=Chevy+Equinox",
    color: "Summit White",
    mileage: 0,
    fuelType: "Gasoline",
    features: ["Chevy Safety Assist", "WiFi Hotspot", "Wireless Charging"],
  },
  {
    id: "car-8",
    make: "Hyundai",
    model: "Tucson",
    year: 2024,
    price: 30200,
    image: "https://placehold.co/600x400/2980b9/ffffff?text=Hyundai+Tucson",
    color: "Amazon Gray",
    mileage: 0,
    fuelType: "Hybrid",
    features: ["SmartSense", "Digital Key", "Bose Premium Audio"],
  },
  {
    id: "car-9",
    make: "Audi",
    model: "A4",
    year: 2024,
    price: 41500,
    image: "https://placehold.co/600x400/8e44ad/ffffff?text=Audi+A4",
    color: "Navarra Blue",
    mileage: 0,
    fuelType: "Gasoline",
    features: ["Quattro AWD", "Virtual Cockpit", "Matrix LED"],
  },
  {
    id: "car-10",
    make: "Jeep",
    model: "Wrangler",
    year: 2024,
    price: 35400,
    image: "https://placehold.co/600x400/27ae60/ffffff?text=Jeep+Wrangler",
    color: "Sarge Green",
    mileage: 0,
    fuelType: "Gasoline",
    features: ["4x4", "Removable Top", "Trail Rated"],
  },
  {
    id: "car-11",
    make: "Nissan",
    model: "Altima",
    year: 2024,
    price: 27500,
    image: "https://placehold.co/600x400/e74c3c/ffffff?text=Nissan+Altima",
    color: "Scarlet Ember",
    mileage: 0,
    fuelType: "Gasoline",
    features: ["ProPILOT Assist", "Intelligent AWD", "Zero Gravity Seats"],
  },
  {
    id: "car-12",
    make: "Volkswagen",
    model: "ID.4",
    year: 2024,
    price: 39500,
    image: "https://placehold.co/600x400/3498db/ffffff?text=VW+ID.4",
    color: "Dusk Blue",
    mileage: 0,
    fuelType: "Electric",
    features: ["IQ.DRIVE", "ID. Light", "Augmented Reality HUD"],
  },
  {
    id: "car-13",
    make: "Subaru",
    model: "Outback",
    year: 2024,
    price: 31200,
    image: "https://placehold.co/600x400/f39c12/ffffff?text=Subaru+Outback",
    color: "Autumn Green",
    mileage: 0,
    fuelType: "Gasoline",
    features: ["EyeSight", "Symmetrical AWD", "X-MODE"],
  },
  {
    id: "car-14",
    make: "Lexus",
    model: "RX",
    year: 2024,
    price: 50500,
    image: "https://placehold.co/600x400/c0392b/ffffff?text=Lexus+RX",
    color: "Nori Green",
    mileage: 0,
    fuelType: "Hybrid",
    features: ["Lexus Interface", "Mark Levinson Audio", "Panoramic Roof"],
  },
  {
    id: "car-15",
    make: "Mazda",
    model: "CX-5",
    year: 2024,
    price: 29900,
    image: "https://placehold.co/600x400/e67e22/ffffff?text=Mazda+CX-5",
    color: "Soul Red Crystal",
    mileage: 0,
    fuelType: "Gasoline",
    features: ["i-Activsense", "Bose Audio", "Heads-Up Display"],
  },
];

export const SAMPLE_CAMPAIGNS: Campaign[] = [
  {
    id: "camp-1",
    title: "Summer Clearance Sale 2024",
    description: "Massive discounts on all 2024 models. Up to 20% off!",
    status: "active",
    type: "banner",
    carIds: ["car-1", "car-2", "car-7"],
    startDate: "2024-06-01",
    endDate: "2024-08-31",
    bannerData: null,
    templateId: "tmpl-1",
    thumbnail: null,
    dimensions: { width: 1200, height: 630 },
    createdAt: "2024-05-15T10:00:00Z",
    updatedAt: "2024-05-15T10:00:00Z",
  },
  {
    id: "camp-2",
    title: "New Arrival: Tesla Model 3",
    description: "Be the first to experience the all-new Model 3.",
    status: "scheduled",
    type: "billboard",
    carIds: ["car-5"],
    startDate: "2024-09-01",
    endDate: "2024-10-31",
    bannerData: null,
    templateId: "tmpl-2",
    thumbnail: null,
    dimensions: { width: 1920, height: 1080 },
    createdAt: "2024-08-20T14:00:00Z",
    updatedAt: "2024-08-20T14:00:00Z",
  },
  {
    id: "camp-3",
    title: "Luxury Showcase: BMW & Mercedes",
    description: "Premium vehicles at competitive prices.",
    status: "draft",
    type: "banner",
    carIds: ["car-4", "car-6"],
    startDate: null,
    endDate: null,
    bannerData: null,
    templateId: null,
    thumbnail: null,
    dimensions: { width: 1080, height: 1080 },
    createdAt: "2024-09-01T09:00:00Z",
    updatedAt: "2024-09-01T09:00:00Z",
  },
  {
    id: "camp-4",
    title: "Off-Road Adventure Event",
    description: "Test drive the Jeep Wrangler and Subaru Outback.",
    status: "completed",
    type: "billboard",
    carIds: ["car-10", "car-13"],
    startDate: "2024-03-01",
    endDate: "2024-04-30",
    bannerData: null,
    templateId: "tmpl-4",
    thumbnail: null,
    dimensions: { width: 1920, height: 1080 },
    createdAt: "2024-02-15T11:00:00Z",
    updatedAt: "2024-05-01T00:00:00Z",
  },
];
