import { BannerTemplate } from "./types";

function makeCanvasJSON(objects: object[], width: number, height: number, bgColor: string): string {
  return JSON.stringify({
    version: "6.0.0",
    objects,
    background: bgColor,
    width,
    height,
  });
}

export const BANNER_TEMPLATES: BannerTemplate[] = [
  {
    id: "tmpl-1",
    name: "Grand Sale",
    description: "Bold red & yellow design with large discount percentage. Perfect for clearance events.",
    category: "sale",
    thumbnail: "",
    dimensions: { width: 1200, height: 630 },
    canvasJSON: makeCanvasJSON(
      [
        {
          type: "Rect",
          left: 0,
          top: 0,
          width: 1200,
          height: 630,
          fill: "#dc2626",
          selectable: false,
        },
        {
          type: "Rect",
          left: 40,
          top: 40,
          width: 1120,
          height: 550,
          fill: "transparent",
          stroke: "#fbbf24",
          strokeWidth: 4,
          rx: 12,
          ry: 12,
          selectable: false,
        },
        {
          type: "Textbox",
          left: 80,
          top: 80,
          width: 600,
          text: "GRAND SALE",
          fontSize: 72,
          fontWeight: "bold",
          fontFamily: "Arial",
          fill: "#fbbf24",
          textAlign: "left",
        },
        {
          type: "Textbox",
          left: 80,
          top: 180,
          width: 500,
          text: "UP TO 50% OFF",
          fontSize: 96,
          fontWeight: "bold",
          fontFamily: "Arial",
          fill: "#ffffff",
          textAlign: "left",
        },
        {
          type: "Textbox",
          left: 80,
          top: 320,
          width: 600,
          text: "Don't miss our biggest sale of the year!\nAll models at unbeatable prices.",
          fontSize: 28,
          fontFamily: "Arial",
          fill: "#fef3c7",
          textAlign: "left",
        },
        {
          type: "Textbox",
          left: 80,
          top: 460,
          width: 300,
          text: "SHOP NOW",
          fontSize: 36,
          fontWeight: "bold",
          fontFamily: "Arial",
          fill: "#dc2626",
          backgroundColor: "#fbbf24",
          textAlign: "center",
          padding: 16,
        },
        {
          type: "Textbox",
          left: 800,
          top: 450,
          width: 350,
          text: "YOUR DEALERSHIP",
          fontSize: 24,
          fontFamily: "Arial",
          fill: "#fca5a5",
          textAlign: "right",
        },
      ],
      1200,
      630,
      "#dc2626"
    ),
  },
  {
    id: "tmpl-2",
    name: "New Arrival",
    description: "Clean modern look with spotlight on a new car model. Elegant and minimal.",
    category: "launch",
    thumbnail: "",
    dimensions: { width: 1200, height: 630 },
    canvasJSON: makeCanvasJSON(
      [
        {
          type: "Rect",
          left: 0,
          top: 0,
          width: 1200,
          height: 630,
          fill: "#0f172a",
          selectable: false,
        },
        {
          type: "Rect",
          left: 0,
          top: 0,
          width: 8,
          height: 630,
          fill: "#3b82f6",
          selectable: false,
        },
        {
          type: "Textbox",
          left: 60,
          top: 60,
          width: 200,
          text: "NEW",
          fontSize: 18,
          fontWeight: "bold",
          fontFamily: "Arial",
          fill: "#0f172a",
          backgroundColor: "#3b82f6",
          textAlign: "center",
          padding: 8,
        },
        {
          type: "Textbox",
          left: 60,
          top: 130,
          width: 600,
          text: "NEW ARRIVAL",
          fontSize: 64,
          fontWeight: "bold",
          fontFamily: "Arial",
          fill: "#ffffff",
          textAlign: "left",
        },
        {
          type: "Textbox",
          left: 60,
          top: 220,
          width: 550,
          text: "Experience the Future of Driving",
          fontSize: 32,
          fontFamily: "Arial",
          fill: "#94a3b8",
          textAlign: "left",
        },
        {
          type: "Textbox",
          left: 60,
          top: 300,
          width: 550,
          text: "Discover cutting-edge technology, unmatched performance, and elegant design in our latest model.",
          fontSize: 22,
          fontFamily: "Arial",
          fill: "#64748b",
          textAlign: "left",
        },
        {
          type: "Textbox",
          left: 60,
          top: 450,
          width: 250,
          text: "LEARN MORE",
          fontSize: 24,
          fontWeight: "bold",
          fontFamily: "Arial",
          fill: "#ffffff",
          backgroundColor: "#3b82f6",
          textAlign: "center",
          padding: 14,
        },
        {
          type: "Textbox",
          left: 60,
          top: 540,
          width: 500,
          text: "Starting from $XX,XXX | Visit Your Dealer Today",
          fontSize: 18,
          fontFamily: "Arial",
          fill: "#475569",
          textAlign: "left",
        },
      ],
      1200,
      630,
      "#0f172a"
    ),
  },
  {
    id: "tmpl-3",
    name: "Clearance Event",
    description: "Urgent styling with countdown feel. Multiple cars with compelling pricing.",
    category: "sale",
    thumbnail: "",
    dimensions: { width: 1200, height: 630 },
    canvasJSON: makeCanvasJSON(
      [
        {
          type: "Rect",
          left: 0,
          top: 0,
          width: 1200,
          height: 630,
          fill: "#f97316",
          selectable: false,
        },
        {
          type: "Triangle",
          left: 900,
          top: -100,
          width: 500,
          height: 500,
          fill: "#ea580c",
          angle: 30,
          selectable: false,
        },
        {
          type: "Textbox",
          left: 60,
          top: 40,
          width: 800,
          text: "CLEARANCE EVENT",
          fontSize: 80,
          fontWeight: "bold",
          fontFamily: "Arial",
          fill: "#ffffff",
          textAlign: "left",
        },
        {
          type: "Textbox",
          left: 60,
          top: 150,
          width: 500,
          text: "EVERYTHING MUST GO!",
          fontSize: 36,
          fontWeight: "bold",
          fontFamily: "Arial",
          fill: "#7c2d12",
          textAlign: "left",
        },
        {
          type: "Textbox",
          left: 60,
          top: 230,
          width: 700,
          text: "Incredible deals on all remaining 2024 inventory.\nPrices slashed across every make and model.",
          fontSize: 26,
          fontFamily: "Arial",
          fill: "#fff7ed",
          textAlign: "left",
        },
        {
          type: "Textbox",
          left: 60,
          top: 370,
          width: 400,
          text: "SAVE UP TO $10,000",
          fontSize: 48,
          fontWeight: "bold",
          fontFamily: "Arial",
          fill: "#ffffff",
          backgroundColor: "#7c2d12",
          textAlign: "center",
          padding: 12,
        },
        {
          type: "Textbox",
          left: 60,
          top: 500,
          width: 500,
          text: "Limited time only! While supplies last.",
          fontSize: 22,
          fontFamily: "Arial",
          fill: "#fed7aa",
          textAlign: "left",
        },
      ],
      1200,
      630,
      "#f97316"
    ),
  },
  {
    id: "tmpl-4",
    name: "Seasonal Special",
    description: "Warm seasonal theme with inviting colors. Great for holiday or seasonal promotions.",
    category: "seasonal",
    thumbnail: "",
    dimensions: { width: 1200, height: 630 },
    canvasJSON: makeCanvasJSON(
      [
        {
          type: "Rect",
          left: 0,
          top: 0,
          width: 1200,
          height: 630,
          fill: "#065f46",
          selectable: false,
        },
        {
          type: "Circle",
          left: 900,
          top: 300,
          radius: 250,
          fill: "#047857",
          selectable: false,
        },
        {
          type: "Circle",
          left: 1000,
          top: 100,
          radius: 150,
          fill: "#059669",
          selectable: false,
        },
        {
          type: "Textbox",
          left: 80,
          top: 80,
          width: 700,
          text: "SEASONAL SPECIAL",
          fontSize: 64,
          fontWeight: "bold",
          fontFamily: "Arial",
          fill: "#ecfdf5",
          textAlign: "left",
        },
        {
          type: "Textbox",
          left: 80,
          top: 180,
          width: 600,
          text: "Celebrate the Season with Amazing Deals",
          fontSize: 30,
          fontFamily: "Arial",
          fill: "#a7f3d0",
          textAlign: "left",
        },
        {
          type: "Textbox",
          left: 80,
          top: 260,
          width: 600,
          text: "Special financing available on select models.\n0% APR for up to 60 months.",
          fontSize: 24,
          fontFamily: "Arial",
          fill: "#d1fae5",
          textAlign: "left",
        },
        {
          type: "Textbox",
          left: 80,
          top: 400,
          width: 260,
          text: "VIEW DEALS",
          fontSize: 28,
          fontWeight: "bold",
          fontFamily: "Arial",
          fill: "#065f46",
          backgroundColor: "#a7f3d0",
          textAlign: "center",
          padding: 14,
        },
        {
          type: "Textbox",
          left: 80,
          top: 520,
          width: 500,
          text: "Your Dealership Name | (555) 123-4567",
          fontSize: 20,
          fontFamily: "Arial",
          fill: "#6ee7b7",
          textAlign: "left",
        },
      ],
      1200,
      630,
      "#065f46"
    ),
  },
  {
    id: "tmpl-5",
    name: "Luxury Showcase",
    description: "Dark, elegant design with premium feel. Perfect for showcasing high-end vehicles.",
    category: "luxury",
    thumbnail: "",
    dimensions: { width: 1200, height: 630 },
    canvasJSON: makeCanvasJSON(
      [
        {
          type: "Rect",
          left: 0,
          top: 0,
          width: 1200,
          height: 630,
          fill: "#18181b",
          selectable: false,
        },
        {
          type: "Rect",
          left: 0,
          top: 610,
          width: 1200,
          height: 20,
          fill: "#d4af37",
          selectable: false,
        },
        {
          type: "Rect",
          left: 0,
          top: 0,
          width: 1200,
          height: 4,
          fill: "#d4af37",
          selectable: false,
        },
        {
          type: "Textbox",
          left: 80,
          top: 80,
          width: 400,
          text: "LUXURY",
          fontSize: 20,
          fontWeight: "bold",
          fontFamily: "Arial",
          fill: "#d4af37",
          letterSpacing: 800,
          textAlign: "left",
        },
        {
          type: "Textbox",
          left: 80,
          top: 130,
          width: 700,
          text: "SHOWCASE",
          fontSize: 80,
          fontWeight: "bold",
          fontFamily: "Arial",
          fill: "#ffffff",
          textAlign: "left",
        },
        {
          type: "Textbox",
          left: 80,
          top: 250,
          width: 600,
          text: "Elevate Your Drive",
          fontSize: 36,
          fontFamily: "Arial",
          fill: "#a1a1aa",
          textAlign: "left",
          fontStyle: "italic",
        },
        {
          type: "Textbox",
          left: 80,
          top: 330,
          width: 600,
          text: "Explore our curated collection of premium vehicles.\nExclusive offers for distinguished buyers.",
          fontSize: 22,
          fontFamily: "Arial",
          fill: "#71717a",
          textAlign: "left",
        },
        {
          type: "Textbox",
          left: 80,
          top: 460,
          width: 240,
          text: "EXPLORE",
          fontSize: 24,
          fontWeight: "bold",
          fontFamily: "Arial",
          fill: "#18181b",
          backgroundColor: "#d4af37",
          textAlign: "center",
          padding: 14,
        },
      ],
      1200,
      630,
      "#18181b"
    ),
  },
  {
    id: "tmpl-6",
    name: "Fleet Deal",
    description: "Business-oriented design for fleet and commercial vehicle promotions.",
    category: "business",
    thumbnail: "",
    dimensions: { width: 1200, height: 630 },
    canvasJSON: makeCanvasJSON(
      [
        {
          type: "Rect",
          left: 0,
          top: 0,
          width: 1200,
          height: 630,
          fill: "#1e3a5f",
          selectable: false,
        },
        {
          type: "Rect",
          left: 0,
          top: 0,
          width: 600,
          height: 630,
          fill: "#0c2340",
          selectable: false,
        },
        {
          type: "Textbox",
          left: 40,
          top: 60,
          width: 520,
          text: "FLEET DEALS",
          fontSize: 56,
          fontWeight: "bold",
          fontFamily: "Arial",
          fill: "#ffffff",
          textAlign: "left",
        },
        {
          type: "Textbox",
          left: 40,
          top: 150,
          width: 520,
          text: "Business Solutions\nfor Every Need",
          fontSize: 32,
          fontFamily: "Arial",
          fill: "#93c5fd",
          textAlign: "left",
        },
        {
          type: "Textbox",
          left: 40,
          top: 270,
          width: 520,
          text: "Volume pricing and custom packages\navailable for businesses of all sizes.",
          fontSize: 22,
          fontFamily: "Arial",
          fill: "#bfdbfe",
          textAlign: "left",
        },
        {
          type: "Textbox",
          left: 40,
          top: 400,
          width: 300,
          text: "GET A QUOTE",
          fontSize: 26,
          fontWeight: "bold",
          fontFamily: "Arial",
          fill: "#ffffff",
          backgroundColor: "#2563eb",
          textAlign: "center",
          padding: 14,
        },
        {
          type: "Textbox",
          left: 650,
          top: 80,
          width: 500,
          text: "5+ Vehicles\n10% Discount",
          fontSize: 40,
          fontWeight: "bold",
          fontFamily: "Arial",
          fill: "#fbbf24",
          textAlign: "center",
        },
        {
          type: "Textbox",
          left: 650,
          top: 250,
          width: 500,
          text: "10+ Vehicles\n15% Discount",
          fontSize: 40,
          fontWeight: "bold",
          fontFamily: "Arial",
          fill: "#34d399",
          textAlign: "center",
        },
        {
          type: "Textbox",
          left: 650,
          top: 450,
          width: 500,
          text: "Free maintenance for 2 years",
          fontSize: 22,
          fontFamily: "Arial",
          fill: "#e0f2fe",
          textAlign: "center",
        },
      ],
      1200,
      630,
      "#1e3a5f"
    ),
  },
];
